"""
A list of 200 general titles for funny or cute animal videos.
These titles are not species-specific and work universally for all animals.
"""

ANIMAL_VIDEO_TITLES = [
    "Too Cute to Function",
    "Absolute Chaos in 15 Seconds",
    "Certified Giggle Material",
    "Oops, That Just Happened",
    "Pure Joy in Motion",
    "This Is What Happiness Looks Like",
    "Adorable or Just Unhinged?",
    "Unexpected Comedy Gold",
    "Tiny Disaster in Progress",
    "Fluffy Mayhem Incoming",
    "Cuteness Level: Maximum",
    "This Made My Day",
    "Who Needs a Plan Anyway?",
    "Instant Smile Generator",
    "Grace? Never Heard of Her",
    "100% Approved by Happiness Experts",
    "More Dramatic Than It Needs to Be",
    "Small Chaos, Big Vibes",
    "This Should Be Illegal (Too Cute)",
    "Clumsy but Confident",
    "Can’t Stop Watching This",
    "Living Their Best Life",
    "Comedic Genius in Action",
    "Wiggle Energy Activated",
    "You Weren’t Ready for This",
    "A Moment of Pure Gold",
    "Too Relatable",
    "Why Is This So Funny?",
    "Cute Things Just Got Cuter",
    "This One Has No Chill",
    "Unstoppable Energy",
    "What Even Was That?",
    "Unexpected Talent Discovered",
    "Tiny Trouble Maker",
    "How Did This Get So Funny?",
    "Short. Sweet. Unforgettable.",
    "Certified Mood Booster",
    "This Should Be in a Museum",
    "Just Vibes and Wiggles",
    "Silly and Proud",
    "Is This Allowed?",
    "The Funniest Thing You'll See Today",
    "Hilarious from Start to Finish",
    "Blink and You'll Miss the Magic",
    "Why Am I Laughing So Hard?",
    "This Went Places",
    "Too Precious for This World",
    "The Internet Was Made for This",
    "It Just Keeps Getting Better",
    "So Wrong, It’s Perfect",
    "I Don’t Know What I Expected",
    "Mildly Unhinged. Fully Adorable.",
    "More Please!",
    "Somehow This Makes Sense",
    "The Laugh You Needed",
    "So Much Personality in One Clip",
    "Unexpected Main Character Moment",
    "They Understood the Assignment",
    "Chaos and Cuteness Collide",
    "This Clip Has Lore",
    "Your Daily Dose of Delight",
    "Pure Comedic Timing",
    "Adorable? Yes. Functional? No.",
    "Just Watch It Again",
    "Legendary Behavior",
    "Cuteness in Its Final Form",
    "Zero Context, 100% Perfect",
    "Little Bean, Big Energy",
    "You’ll Be Rewatching This",
    "Caught in 4K Being Adorable",
    "Maximum Wholesome Energy",
    "Comedic Timing: Nailed It",
    "Soft. Chaotic. Glorious.",
    "They Did It Again",
    "No Notes. 10/10.",
    "The Soundtrack of Joy",
    "Big Mood in a Small Package",
    "This Was Not in the Script",
    "Main Character Energy",
    "Wholesome with a Side of Chaos",
    "Unscripted Genius",
    "This Clip Is a Hug",
    "One Word: Iconic",
    "Absolutely Uncalled For (But I Love It)",
    "Weird and Wonderful",
    "So Good It Feels Illegal",
    "I Feel Seen",
    "Unexpectedly Amazing",
    "One Second of Chaos",
    "Perfectly Imperfect",
    "Best Thing You’ll See Today",
    "The Definition of Unbothered",
    "This Is What Joy Looks Like",
    "So Small. So Powerful.",
    "Viral in 3…2…1…",
    "No Words. Just Vibes.",
    "Little Things, Big Feels",
    "Why Does This Feel Personal?",
    "Every Frame Is Art",
    "Go Ahead. Smile.",
    "A Masterpiece of Mess",
    "The Confidence! The Drama!",
    "Bite-Sized Brilliance",
    "So Unnecessary. So Amazing.",
    "Running on Pure Instinct",
    "A Lesson in Comedy",
    "Simply Unmatched",
    "Wholesome Chaos in Motion",
    "Caught in the Act",
    "Your Mood Booster Today",
    "Certified Internet Gold",
    "So Random. So Right.",
    "Cute. Clumsy. Confused.",
    "A Small Star Is Born",
    "The Art of the Flop",
    "This Made Me Laugh Too Hard",
    "Still Processing This Clip",
    "A Fever Dream, But Adorable",
    "Short and Sweet Madness",
    "Felt Cute, Might Delete Later",
    "This Energy Is Unmatched",
    "One of a Kind",
    "Unexpected Star of the Day",
    "Wholesome? Absolutely.",
    "What a Journey",
    "Comedy You Can’t Script",
    "Snack? Attack.",
    "Honestly Just Vibes",
    "Drama in 10 Seconds",
    "This Shouldn’t Be This Funny",
    "Pure Magic Captured",
    "Viral Material Detected",
    "No Chill. Just Thrill.",
    "So Much Sass in So Little Time",
    "You’re Welcome",
    f"100% Good Vibes",
    "A Moment of Unfiltered Joy",
    "This Is Art",
    "Caught Being Themselves",
    "The Energy Is Chaotic Good",
    "Wholesome Mayhem",
    "Unexpectedly Legendary",
    "So Weird. So Right.",
    "Cutest Chaos You’ll See All Day",
    "I Need More of This",
    "An Icon in the Making",
    "Best Use of 15 Seconds",
    "The Face of Pure Mischief",
    "This Is Why We Have the Internet",
    "Not What I Expected",
    "Too Funny Not to Share",
    "Simply Incredible",
    "Smol. Floof. Chaos.",
    "They Really Said ‘Drama’",
    "You Can't Script This",
    "Unexpected Genius",
    "Instant Favorite",
    "Just… Wow",
    "Vibe Check: Passed",
    "10 Seconds of Joy",
    "Absolutely Feral (In a Good Way)",
    "Perfectly Weird",
    "This Clip Deserves an Award",
    "True Internet Royalty",
    "Laughing? Crying? Both?",
    "Iconic Behavior Only",
    "Cuteness With No Context",
    "What Even Happened?",
    "This Energy Is Unmatched",
    "One of the Greats",
    "Internet: You Win",
    "Can’t Look Away",
    "Proof That Chaos Can Be Cute",
    "What a Ride",
    "Effortlessly Entertaining",
    "Short. Silly. Supreme.",
    "I Can’t Stop Laughing",
    "Who Gave Them a Camera?",
    "Big Energy in a Small Moment",
    "Instant Replay Worthy",
    "The Best Kind of Nonsense",
    "Tiny Moment, Huge Impact",
    "This One Lives in My Head Now",
    "Nothing Makes Sense, and That’s Fine",
    "Let Me Just Watch That Again",
    "Absolutely Zero Regret",
    "That Escalated Hilariously",
    "An Unfiltered Masterpiece",
    "Maximum Impact in Minimum Time",
    "You Had to Be There (But You Are)",
    "This Was Not on My Bingo Card",
    "Thanks, I Needed This",
    "A Classic in the Making",
    "It’s Giving Main Character Vibes",
    "Can We Talk About This?",
    "They Understood the Assignment",
    "This Belongs in a Museum",
    "Masterclass in Chaos",
    "Peak Internet",
    "Mood: Captured",
    "Silly Little Clip, Big Joy",
    "I Feel Better Now",
    "This Is the Vibe Today",
    "What Did I Just Watch?",
    "This Is Pure Cinema",
]

"""
A list of 50 short and uplifting video descriptions
for funny or cute animal clips. These are general and
work for all types of animals and platforms.
"""

ANIMAL_VIDEO_DESCRIPTIONS = [
    "Spread the smile — share this with a friend!",
    "Warning: This may cause uncontrollable smiling",
    "Feeling down? This will fix it.",
    "You didn’t know you needed this today",
    "Just a little reminder that life is cute.",
    "Joy comes in small, furry packages!",
    "Proof that happiness is real",
    "Brighten someone’s day — send this!",
    "Share the love, spread the laughs",
    "Too cute not to share!",
    "Fluff therapy in progress...",
    "This made my heart do a happy dance",
    "Good vibes only. Pass it on!",
    "Sometimes all you need is this video.",
    "Can we all agree this is a masterpiece?",
    "Short, silly, and totally worth it.",
    "If you smiled, mission accomplished",
    "Instant serotonin booster",
    "You’ll want to watch this twice — maybe more.",
    "Tag someone who needs a smile today!",
    "Who else rewatched this 3 times?",
    "Small joy. Big impact.",
    "Guaranteed mood-lifter",
    "Cute and chaotic — our favorite combo!",
    "Keep this energy in your life",
    "This is your sign to smile today",
    "Because everyone deserves a giggle break.",
    "The internet at its purest form",
    "One word: awwww!",
    "This should be studied for how adorable it is.",
    "Why cry when you can laugh at this?",
    "Friendly reminder: joy is free!",
    "Sometimes life’s just about cute moments like this.",
    "You’re welcome in advance!",
    "Feel better, instantly.",
    "Tag your ‘let’s watch cute videos’ friend!",
    f"100% good vibes detected.",
    "Share the joy — make someone’s day",
    "Certified adorable moment!",
    "Smiles guaranteed or your giggles back.",
    "Just in case you needed a reason to laugh today.",
    "This is pure, unfiltered joy",
    "One clip. Endless happiness.",
    "Yes, the internet is still good sometimes.",
    "When life gives you stress, watch this.",
    "This is what peace looks like",
    "A perfect example of why animals rule.",
    "This right here is happiness in motion.",
    "You didn’t ask, but you needed this.",
    "Nothing to see here — just perfection",
]