fun_fact_subjects = [
    "Octopuses", "Bananas", "Sleep", "Space", "Sharks", "Rainbows",
    "Music", "Ice Cream", "Languages", "Ancient Egypt", "Time",
    "Dreams", "Color Blue", "Dolphins", "Memory", "Robots", "Fire",
    "Snails", "Gravity", "Lightning", "Black Holes", "Penguins", "Coffee",
    "Cats", "Chocolate", "Dinosaurs", "Stars", "Jellyfish", "Mount Everest",
    "Butterflies", "Honey", "Antarctica", "Tornadoes", "Quantum Physics",
    "Camels", "The Moon", "Volcanoes", "Crocodiles", "Artificial Intelligence",
    "Laughter", "Brain", "Northern Lights", "Pyramids", "Elephants", "Spiders",
    "Mars", "Seaweed", "Electric Eels", "Bamboo", "Chameleons", "Whales",
    "Solar Flares", "Coral Reefs", "Polar Bears", "Venus Flytraps", "Auroras",
    "Bioluminescence", "Platypuses", "Fibonacci Sequence", "Diamond Rain",
    "Parrots", "Human Eye", "Comets", "Giant Squid", "Atlantis", "Snowflakes",
    "Magnetism", "Mosquitoes", "Sahara Desert", "Butter", "Mona Lisa",
    "Blue Whales", "Zombie Ants", "Great Wall of China", "Photosynthesis",
    "DNA", "Symmetry", "Sandstorms", "Cacti", "Electricity", "Deep Sea Creatures",
    "Ninjas", "Samurai", "Meteorites", "Koalas", "Aurora Borealis", "Rubik's Cube",
    "Gravity Waves", "Virtual Reality", "Flying Fish", "Origami", "Mushrooms",
    "Anesthesia", "Rainforests", "Ants", "Sushi", "Perfume", "Crystals",
    "Silk", "Peacock Feathers", "Ancient Rome", "Hurricanes", "Penguin Colonies",
    "Hieroglyphics", "Desert Plants", "Glow Worms", "Airplanes", "Ghost Towns",
    "Chess", "Coconuts", "Tsunamis", "Haunted Houses", "Windmills", "Geysers",
    "Human Brain", "Siberia", "Sea Turtles", "Carnivorous Plants", "Pineapples",
    "Quantum Entanglement", "Galaxies", "Goldfish Memory", "Fingerprint Patterns",
    "Pearls", "Meteors", "Snow Leopards", "Frogs", "Icebergs", "Roman Numerals",
    "Speed of Sound", "Deep Space", "Whirlpools", "Butterfly Migration",
    "Moonlight", "Optical Illusions", "Geckos", "Mayan Civilization", "Vikings",
    "Submarines", "Saturn's Rings", "Maple Syrup", "Solar Eclipse", "Gravity Anomalies",
    "Coral Bleaching", "Marsupials", "Stonehenge", "Clouds", "Squirrels",
    "Human Heart", "Dragonflies", "Egyptian Tombs", "Chocolate Production",
    "Desert Animals", "Piranhas", "Paper Money", "Amber", "Fireflies", "Tea",
    "Sound Waves", "Jupiter", "Tree Rings", "Lightning Bugs", "Avalanches",
    "Glass Making", "Shipwrecks", "Space Station", "Deep Ocean Trenches",
    "Spicy Foods", "Kangaroos", "Sahara Animals", "Pigeons", "Underwater Cities",
    "Blood Cells", "Human Bones", "Desertification", "Mirages", "Space Junk",
    "Honeybees", "Deserts", "Aurora Australis", "Microwaves", "Greek Mythology",
    "Ancient China", "Bermuda Triangle", "Ice Ages", "Lunar Landings", "Cave Paintings",
    "Tigers", "Mars Rovers", "Neanderthals", "Gravity on Different Planets",
    "Earthquakes", "Compost", "Black Widow Spiders", "Pufferfish", "Pearl Diving",
    "Space Telescopes", "Mythical Creatures", "Ship Navigation", "Human Skin",
    "Jet Engines", "Space Colonization", "Ancient Olympics", "Meteor Showers",
    "Astronauts", "Wax Museums", "Ice Sculptures", "Robotics", "Hot Springs",
    "Poison Dart Frogs", "Bullet Trains", "Snowboarding", "Desert Mirage",
    "Bats", "Helium Balloons", "Salt Mines", "Oceans", "Steam Engines",
    "Space Exploration", "Ancient Libraries", "Ocean Currents", "Golden Ratio",
    "Volcanic Lightning", "Biodegradable Plastics", "Black Panthers", "Leaf-cutter Ants",
    "Space Food", "Mantis Shrimp", "Crop Circles", "Deep-sea Vents", "Spacewalks",
    "Flamingos", "Undersea Volcanoes", "Supernovas", "Alien Life", "Nanotechnology",
    "Olympic Games", "Lunar Eclipses", "Ancient Temples", "Magic Tricks",
    "Bird Migration", "Meteor Impacts", "Rainforests Animals", "Space Tourism",
    "Ancient Greek Theatre", "Aurora Colors", "Jet Packs", "Chocolates History",
    "Whale Songs", "Space Suits", "Black Sand Beaches", "Alchemy", "Polar Explorations",
    "Dinosaurs Extinction", "Hot Air Balloons", "Volcano Myths", "Medieval Castles",
    "Oceanic Trenches", "Marine Snow", "Vortexes", "Tropical Islands", "Coral Islands",
    "Galactic Centers", "Ancient Scripts", "Deep Space Signals", "Mystery Lights",
    "Solar Storms", "Gravity Assist", "Remote Islands", "Space Farms", "Pirates",
    "Moon Bases", "Solar Sails", "Unexplained Phenomena", "Insect Vision", "Space Debris",
    "Alien Signals", "Lost Civilizations", "Time Travel", "Quantum Computers",
    "Space Elevators", "Sunspots", "Dark Matter", "Exoplanets", "Astronomy Myths",
    "Magnetic Poles", "Microgravity", "Parallel Universes", "Dwarf Planets", "Cosmic Rays"
]